### ISSUE TITLE
Question about CFG to represent network protocol

### ISSUE THREAD

**Issue by 50u1w4y** [pevalme/HTTPValidator#3]
Hello, thanks for your sharing.

I have a smattering knowledge with CFG and network protocol, may I ask you some questions?

At your paper, after making the unbounded field to fixed field, HTTP can be represented as CFG. So, can we say that any network protocol can be represented as CFG as long as we make the unbounded fields to fixed fields?

In compiler and interpreter community, if a language can be represent as CFG, then we can also generate a equivalent AST to represent it. Since HTTPValidator lies on the task of input validation, can HTTPValidator also make HTTP to reprensent as AST? Specifically, replacing a subtree in the AST still keep the syntactically correct.

**Comment by pierreganty** [comment]
Hello.

I am not sure I understand your question.
Let me try to answer anyways.

Given an HTTP message that is valid you can construct not one but several ASTs.
In particular you would have one AST for each grammar used to define HTTP messages.
In our [paper](https://arxiv.org/abs/1610.07198) explaining the theory behind HTTP validator you have the following table about the number of CFG involved in validating HTTP messages.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/2111160/165698095-855d58b8-9d8f-47c0-bf79-084f374eeb8e.png">
Following the table given a valid HTTP message you would have one AST for the ABNF of HTTP, one for length fields, one for comparison, etc.

If I happen to have misunderstood you please try to reformulated your question and perhaps include an example which always facilitates communication.

In any case, thank you for your interest and have a nice day.

**Comment by 50u1w4y** [comment]
Hello, thanks for your reply.

And another question, can we say that most of the protocols can be represented if we follow the work done in the paper, since HTTP contains almost all of the features that have been
used in the literature to dispute the suitability of CFLs for parsing network
protocols.

Hope you have a nice day too. : )

**Comment by pierreganty** [comment]
That's what we hope but we cannot say for sure. One should carefully examine all the features being used and check for each of them whether or not they can be encoded as CFL. If you have a feature you are not sure of please drop me an email and we will see what we can do.

**Comment by 50u1w4y** [comment]
Got it, thanks for your explanation and help again.
